baseURL = "https://n4r1b.com"
title = "Up is Down and Black is White"

theme = "hello-friend-ng"

DefaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsUseClasses = true
PygmentsStyle = "monokai"
rssLimit  = 10  # Maximum number of items in the RSS feed.


archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"


buildDrafts  = false
buildFuture  = true
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

googleAnalytics = "UA-157901457-1"

[blackfriday] 
  hrefTargetBlank = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[markup.goldmark.renderer]
  unsafe= true


[author]
  name = "n4r1b"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Reverse Engineer blog by n4r1b"
  keywords = "RE, blog, Reversing, Security, Kernel, infosec"
  images = ["https://n4r1b.com/images/cover.jpg"]

  gitUrl = "https://github.com/n4r1b/n4r1b-hugo/commit/" 

  homeSubtitle = "n4r1b"

  customCSS = ["/css/syntax.css"]
  customJS  = ["/js/script.js"]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
    logoText     = "n4r1b/re$"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/n4r1b"

  [[params.social]]
    name = "github"
    url  = "https://github.com/n4r1b"

[languages]
  [languages.en]
    subtitle  = "n4r1b"
    weight    = 1

  [languages.es]
    subtitle  = "n4r1b"
    weight    = 2


[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
